config/routes.rb
Hnclone::Application.routes.draw do

  root to: 'links#index'
  
  resources :votes, :only => [:create]

  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :presence => true, :uniqueness => true, :format => {:with => URI.regexp}
  validates :title, :presence => true

  has_many :votes

  scope :desc, order('created_at DESC')
  scope :by_votes, joins(:votes).group(:link_id).order("count(link_id) DESC").select("links.*, count(link_id) as vote_count")

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :link
  validates :link, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.by_votes.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])
    
    if @link.save
      redirect_to links_path, :notice => "Link added"
    else
      render "new"
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :voted?

  def create
    link = Link.find(params[:vote][:link_id])
    link.votes.create  # created Vote obj, with link_id automatically set
    cookies[:voted] = "true"
    redirect_to links_path
  end

private

  def voted?
    redirect_to(links_path, alert: "You cant vote more than once per Link") if cookies[:voted]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hnclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="brand" href="#">
				  DevNewsCamp
				</a>
				<ul class="nav">
				  <li class="active">
				    <a href="#">Home</a>
				  </li>
				  <li><a href="#">Submit</a></li>
				  <li><a href="#">New</a></li>
				</ul>
				<ul class="nav pull-right">
           <li class="divider-vertical"></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
             <ul class="dropdown-menu">
               <li><a href="#">Edit Account</a></li>
               <li class="divider"></li>
               <li><a href="#">Log out</a></li>
             </ul>
           </li>
         </ul>
	    </div>
	  </div>
	</div>
  <div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/links/index.html.erb
<%= content_tag(:h3, "#{flash[:alert]}", class: 'alert') if flash[:alert] %>
<h1>Welcome to HNClone</h1>
Please don't sue us for copyright.
<ul>
<% @links.each do |link| %>
  <li>
	<%= link_to link.title, link.url %>                                                                    Lin
    <br />
    [Votes: <%= link.vote_count %>]
  </li>

<%= form_for Vote.new do |f| %>
<%= f.hidden_field :link_id, :value => link.id %>
<%= f.submit "vote up" %>
<% end %>

<% end %>
</ul>



<%= link_to "Add link", new_link_path %>

app/views/links/new.html.erb
<div class="row">
      <%= form_for (@link), :class => "form-horizontal" do |f| %> 
			        <fieldset>
			          <legend>Submit a Link</legend>
								<% @link.errors.full_messages.each do |msg| %>
									<p>
								      <strong><%= msg %></strong>
									</p>
								<% end %>
			          <div class="control-group">
									<%= f.label :title, :class => "control-label" %>
			            <div class="controls">
										<%= f.text_field :title, :class => "input-xlarge"  %>
			            </div>
			          </div>
								<div class="control-group">
									<%= f.label :url, :class => "control-label" %>
			            <div class="controls">
										<%= f.text_field :url, :class => "input-xlarge"  %>
			            </div>
			          </div>
			          <div class="form-actions">
									<%= f.submit "Add", :class => "btn btn-primary" %>
			          </div>
			        </fieldset>
			<% end %>	
</div>